### ISSUE TITLE
Possible issue with libSkiaSharp.so on v10.8.5

### ISSUE THREAD

**Issue by GreenBlood** [Thefrank/jellyfin-server-freebsd#28]
Hi, to begin with, nice job on this build, i've used it for some time now and it is *really* helpfull so kudos to you :heart: :)

I've juste installed 10.8.5 from your repo, and while the WebUI seems to work correctly, I've noticed a lot of error regarding libSkia ni Jellyfin logs.
Normally I would've opened an issue on the parent project directly but as you seem to ship build of libSkia also I figured it might be related.

I've also noticed that in the[ "tag" body](https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.8.5) it says the following : 
> Skia built from tags/v2.88.2
> https://github.com/mono/skia/releases/tag/v2.88.0

Yet the link is for 2.88.0 and no 2.88.2 seems to exist on the mentionned repo (at least not yet)

Following is the libSkia related error I see in my logs : 

```
[2022-10-01 20:40:36.636 +02:00] [ERR] [77] Emby.Drawing.ImageProcessor: Error encoding image
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at SkiaSharp.SKBitmap.Decode(String filename)
   at Jellyfin.Drawing.Skia.SkiaEncoder.Decode(String path, Boolean forceCleanBitmap, Nullable`1 orientation, SKEncodedOrigin& origin)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetBitmap(String path, Boolean autoOrient, Nullable`1 orientation)
   at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat outputFormat)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
```

**Comment by Thefrank** [comment]
Typo on that version listed but it does look like it wants 2.88.1+ now.
This was not caught by Jellyfin's tests (or if it was, it generated no failure). I will get an updated lib upload soon(ish) and repackage the PKG for those that don't want to manually overwrite things.

Thanks for letting me know about this and sorry about mess up!

**Comment by Thefrank** [comment]
@GreenBlood I updated the Skia version and repackaged the PKG. Let me know if you still have issues

**Comment by GreenBlood** [comment]
Sorry my bad, I did not see the notification update for this issue. It's all fixed now with the new package, no error to be seen, thanks again for your work @Thefrank :)
