### ISSUE TITLE
Media is not playing due to "ffmpeg path not set"

### ISSUE THREAD

**Issue by SyntaxisCS** [Thefrank/jellyfin-server-freebsd#35]
Hey I recently did a reinstall of truenas during an upgrade of my server and I had jellyfin running in a jail previously and due to the upgrade I had to reinstall all of my jails includng the jellyfin one. I followed the installation instructions as I had before and it went flawlessly and I was able to go in and create my users again and add my media. However upon trying to watch a movie it started to load longer than usual and it never ended up playing. So I checked the logs and found this. (Bottom of post)

The main issue seems to be regarding ffmpeg as "FFmpeg path not set." is one of the errors along with errors involving ffprobe. I then when to the admin panel of the server > Playback and saw that the ffmpeg path field was blank. I then went into the shell and ran ``` pkg install ffmpeg ``` hoping that this would have fixed it but it did not :(. I then tried to set the field in th admin panel to '/usr/local/bin' as this is where files named ffmpeg and ffprobe were located however it said that it could not find ffmpeg in that folder. I am not unsure as to where I can go from here. I installed the latest version "10.8.8" and even tried downgrading to "10.8.5" but to no avail.

I know in the release notes you said that it did not include ffmpeg but I installed my original jellyfin install around the beginning of November 2022 so I don't know why it would have worked then. Any help is appreciated and if you need anything else let me know!
```
[2023-01-08 16:08:33.984 -08:00] [ERR] [3] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/be9012a1-b8e6-128e-b693-04deb70a23ee/live.m3u8".
System.ArgumentException: FFmpeg path not set.
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetLiveHlsStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 enableSubtitlesInManifest)
   at lambda_method871(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-01-08 16:08:35.571 -08:00] [INF] [33] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Media Player" "1.7.1" playing "Interstellar". Stopped at "0" ms
[2023-01-08 16:08:35.727 -08:00] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjcuMSAod2luZG93cy14ODZfNjQgMTApfDE2NjgxOTU0MDY3NjU1-58b7311b19964aaa9e61ffdaa14d3656-be9012a1b8e6128eb69304deb70a23ee"
[2023-01-08 16:08:35.728 -08:00] [INF] [25] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 01/08/2023 16:08:35
[2023-01-08 16:08:35.728 -08:00] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2023-01-08 16:08:51.734 -08:00] [ERR] [27] Emby.Server.Implementations.IO.ManagedFileSystem: Reading the file size of the symlink at "/sys" failed. Marking the file as not existing.
System.IO.FileNotFoundException: Could not find file '/sys'.
File name: '/sys'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
[2023-01-08 16:09:20.833 -08:00] [INF] [31] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-01-08 16:09:32.839 -08:00] [INF] [27] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2023-01-08 16:12:02.816 -08:00] [WRN] [8] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "172.20.0.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-01-08 16:12:02.855 -08:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "172.20.0.1" closed
[2023-01-08 16:12:23.292 -08:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "172.20.0.1" request
[2023-01-08 16:12:26.859 -08:00] [INF] [8] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Attempting to update encoder path to "/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin". pathType: "Custom"
[2023-01-08 16:12:26.861 -08:00] [ERR] [8] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Error validating encoder
System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin' with working directory '/'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetProcessOutput(String path, String arguments, Boolean readStdErr, String testKey)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
[2023-01-08 16:12:26.866 -08:00] [ERR] [8] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/System/MediaEncoder/Path".
MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.UpdateEncoderPath(String path, String pathType)
   at Jellyfin.Api.Controllers.ConfigurationController.UpdateMediaEncoderPath(MediaEncoderPathDto mediaEncoderPath)
   at lambda_method922(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
```

**Comment by Thefrank** [comment]
`FFmpeg path not set.` is fine...usually.
 Use that only if you are using a custom `FFmpeg` PATH/build. You can try `/usr/local/bin/ffmpeg`  as its location if you want to manually set it.

Can you also try and playback media inside the webclient (jellyfin-web)? The server looks like its reporting `"Jellyfin Media Player" "1.7.1"` as its player. Which should not be an issue but will help with some troubleshooting here.

**Comment by SyntaxisCS** [comment]
I tried playing media inside of jellyfin-web and I received the error "Playback Error this client isn't compatible with hte media and the server isn't sending a compatible media format" I have played this media before and it is all in .mp4 file types. In the logs file I received this output

```
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2023-01-08 18:12:27.739 -08:00] [INF] [24] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Charley". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2023-01-08 18:12:27.739 -08:00] [INF] [24] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/media/Movies/Alien Resurrection (1997)/Alien Resurrection (1997) - Special Edition.m4v", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported ) "media:/videos/feb716cb-5b40-1836-3b33-5c0a77a24e8f/master.m3u8?MediaSourceId=feb716cb5b4018363b335c0a77a24e8f&VideoCodec=h264&AudioCodec=aac,mp3&VideoBitrate=139808000&AudioBitrate=192000&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=4d4793d51fed875b8dfe32c80e413d67&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-rangetype=SDR&h264-level=52&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported"
[2023-01-08 18:12:27.866 -08:00] [INF] [24] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-01-08 18:12:27.871 -08:00] [ERR] [24] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/feb716cb-5b40-1836-3b33-5c0a77a24e8f/live.m3u8".
System.ArgumentException: FFmpeg path not set.
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetLiveHlsStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 enableSubtitlesInManifest)
   at lambda_method1193(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-01-08 18:12:27.915 -08:00] [INF] [31] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.8" playing "Alien Resurrection". Stopped at "0" ms
[2023-01-08 18:12:28.068 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwNy4wLjAuMCBTYWZhcmkvNTM3LjM2fDE2NjkwNTU3MzYzNDE1-58b7311b19964aaa9e61ffdaa14d3656-feb716cb5b4018363b335c0a77a24e8f"
[2023-01-08 18:12:28.068 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 01/08/2023 18:12:28
[2023-01-08 18:12:28.068 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : "172.20.0.1"
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = "90f4d2fcff6ed0c7356a4e807d273415"
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = "58b7311b19964aaa9e61ffdaa14d3656"
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 2
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = ""
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = "58b7311b19964aaa9e61ffdaa14d3656"
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = "na"
[2023-01-08 18:12:39.945 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = "Jellyfin Web"
[2023-01-08 18:12:39.947 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = "Chrome"
[2023-01-08 18:12:39.947 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = "Alien: Covenant"
[2023-01-08 18:12:39.947 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = "90f4d2fcff6ed0c7356a4e807d273415"
[2023-01-08 18:12:39.947 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = "Movie"
[2023-01-08 18:12:39.947 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[2023-01-08 18:12:39.947 -08:00] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[2023-01-08 18:12:46.993 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : "172.20.0.1"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = "feb716cb5b4018363b335c0a77a24e8f"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = "58b7311b19964aaa9e61ffdaa14d3656"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 2
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = ""
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = "58b7311b19964aaa9e61ffdaa14d3656"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = "na"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = "Jellyfin Web"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = "Chrome"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = "Alien Resurrection"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = "feb716cb5b4018363b335c0a77a24e8f"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = "Movie"
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[2023-01-08 18:12:46.994 -08:00] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
```

**Comment by Thefrank** [comment]
This looks like permissions/ownership might be messed up. 
I did a quick test in a new jail where I just installed my pkg and was not able to reproduce this. Jellyfin was able to find FFmpeg in path and records it as just "ffmpeg" in Dashboard -> Server -> Playback.

As for logs:
Dashboard -> Advanced -> Logs. 
There should be logs named `log_YYYYMMDD.log` 
and, if ffmpeg is working, `FFmpeg.PLAYBACK-DATESTAMP_SOME_HASH_VALUES.log`

If you still have my pkg in the jail try running `pkg install -f jellyfinserver-10.8.8.pkg` to force reinstall it.

**Comment by SyntaxisCS** [comment]
Ok I will try doing the force reinstall that you mentioned first when I get home and if that doesn't work I will just delete the jail and create a new one and see where I am after that. I'll try this in a couple hours and will let you know what the results are.

**Comment by SyntaxisCS** [comment]
After completely destroying the jail and rebuilding it jellyfin started working. I am not 100% sure as to what caused this but I have an idea that setting ipv6 to inherit had something to do with it. I 100% did this for my original installation in November and I thought I did it the first time but I'm not exactly 100% sure that I did and I didn't check before I destroyed the jail so I can't be sure.

Anyway jellyfin is working now and I sincerely thank you for your work on this package, Thefrank. For anyone who has this issue in the future please ensure you setup the jail settings correctly like ipv6=inherit and raw_sockets and mlock!

**Comment by TNAS123** [comment]
Hi @SyntaxisCS sorry to comment on this 8 mi this later but I have this same exact issue and can't figure out why it happened and how to fix it. Did you create a new jail for Jellyfin manually or use the one created by the plugin installer? Any step by step advice would be appreciated. Thanks

**Comment by SyntaxisCS** [comment]
> Hi @SyntaxisCS sorry to comment on this 8 months later but I have this same exact issue and can't figure out why it happened and how to fix it. Did you create a new jail for Jellyfin manually or use the one created by the plugin installer? Any step by step advice would be appreciated. Thanks

Not a problem, happy to help! As far as I know the issue must have been with the configuration of the jail. I created a new jail with the recommended settings and it just worked after installing the package. So I would try that first, just completely destroy the jail and start a new one. I haven't dealt with the new versions of this package as I haven't updated since the reinstall 8 months ago so maybe something changed with the newer versions but that seems unlikely. Let me know if that fixes it! Sorry I couldn't be of more help.
