### ISSUE TITLE
I uninstalled the plugin and am getting an error attempting to reinstall see below missing user jellyfinserver?

### ISSUE THREAD

**Issue by pasha-19** [Thefrank/jellyfin-server-freebsd#48]
Error: (PlugnName) had a failure Exception: RuntimeError Message: Last 10 lines: Traceback (most recent call last): File "/usr/local/bin/jellyfin_updater", line 138, in < module > InstallOrUpdate() File "/usr/local/bin/jellyfin_updater", line 132, in InstallOrUpdate InstallService() File "/usr/local/bin/jellyfin_updater", line 106, in InstallService raise Exception('Failed to get GitHub url...') Exception: Failed to get GitHub url... pw: user `jellyfinserver' does not exist Partial plugin destroyed

**Comment by spz2k9** [comment]
Oh didn't know the pkg wasn't produced anymore. I'll check to update the plugin to take the pkg from the repo since it's been updated in the quarterly. I should be able to do a patch by the weekend.

**Comment by pasha-19** [comment]
Yes, TrueNAS Core fully updated.

I also created a user and group using UID and GID 710 in TrueNAS Core proper to set security in the main pool that seemed to suffice across the mount point for the jail.  I deleted that user and group and am attempting to install again.  From what you say it will fail and I will wait for an update this weekend.  Thanks for the quick response.

**Comment by regimeG** [comment]
Does this mean the community plugin in TrueNAS can not be updated by just clicking "update"? My installation seams to be broken as well after updating a few minutes ago. I can't get any connection to my Jellyfin Server. Can you please guide me to get a proper installation?
Thanks in advance!

**Comment by Thefrank** [comment]
I have add the pkg from the pkg mirror to the repo [release](https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.8.10). This should (hopefully) solve the issue until the TrueNAS plugin is updated to use FreeBSD pkg mirror instead of this repo

**Comment by regimeG** [comment]
Thank you very much! I updated again and the installation went through flawless. But I still can't reach the Server. Do you have any suggestions?

**Comment by spz2k9** [comment]
Normally the admin web page should be available in the plugin section. Can you verify if the link of that page is valid?

**Comment by regimeG** [comment]
Yes, the IP address displayed is the same as the IP address in the router reserved specifically for Jellyfin. The router also shows the server as active. Nevertheless, Firefox cannot establish a connection. It was the same with the last update and I had to reinstall everything. I would like to avoid that this time if possible.

Thanks for the support ;-)

**Comment by spz2k9** [comment]
@Thefrank I just updated the install script and removed the updater script so the packages all comes from the Repo now.

**Comment by spz2k9** [comment]
@regimeG That's weird... maybe it's a problem with the commands in the old install script. Can you open a terminal in this jail and do a 'top' command to see if the jellyfin server process is running ?

**Comment by regimeG** [comment]
There are just a few processes visible for me. I can identify "top" of course, "syslogd", "csh", "login", "cron" and three times "dhclient".

**Comment by regimeG** [comment]
> @Thefrank I just updated the install script and removed the updater script so the packages all comes from the Repo now.

Should I run the update again?

**Comment by spz2k9** [comment]
I don't think the update will fix this problem since update only update the pkg installed from the official repo... I've sent a pull request for this like 5 mins ago... but it won't be included in TrueNas until the next release (probably in two weeks) and that's if someone from TrueNas Team merge my pull request.

The fix without recreating the jail would be to run thoses commands : 

pw group mod video -m jellyfin

sysrc -f /etc/rc.conf jellyfin_enable="YES"

service jellyfin start 2>/dev/null

**Comment by regimeG** [comment]
Should the commands being executed directly in the shell from the jail or in the global shell of TrueNAS?

**Comment by spz2k9** [comment]
They have to be executed inside the jail... it can be done with a shell connected to the jail.... or in the jail UI there's a shell option to open a shell for that jail.

**Comment by regimeG** [comment]
Ok, after inserting the first command the following comes back: pw: user 'jellyfin' does not exist

**Comment by spz2k9** [comment]
oh okay... so you'll need to run this one first : 

pkg install -y jellyfin

**Comment by regimeG** [comment]
Just to be sure. In addition to the installed community plugin?

**Comment by spz2k9** [comment]
Well you'll have both package the files should overrites themselves, but if you want to uninstall the community package first you'd do : 

pkg remove -y jellyfinserver

Then install the official package and then the 3 other commands.

**Comment by regimeG** [comment]
Ok, all done.

**Comment by spz2k9** [comment]
Good, if everything went as planned... it should work now.

**Comment by regimeG** [comment]
There is a note that "allow_mlock=1" is important for using in a jail. Is it important or can we ignore it?

**Comment by spz2k9** [comment]
That's only usefull when creating the jail... since the jail is already created you'll only need the commands to configure and start the service.

**Comment by spz2k9** [comment]
I've reran the install and I now understand it's this message : 

`If you are running this in a jail please set "allow_mlock=1" or similar
for this jail otherwise the program will fail to start.`

You can ignore all those messages, thoses commands have already been ran at jail creation.

**Comment by regimeG** [comment]
Ok, thank you so much for your patience! At least I can connect to the server but have to reconfigure everything again. I'll do it again and lets hope that the next update will be done without that issue ;-)
Glad to have Jellyfin for my NAS!

**Comment by spz2k9** [comment]
No probl. Normally the update button from TrueNas UI should update correctly when the pull request on the plugin will be merge in TrueNas. It will be in the next TrueNas update if I've made the fix in time.

**Comment by regimeG** [comment]
How can I support your effort around Jellyfin and TrueNAS coming together?

**Comment by spz2k9** [comment]
It's all good... the plugin had been approved in the past, I don't think they'll mind getting an update... it's just a mater of time before they approve the update.

**Comment by pasha-19** [comment]
I took a chance; I am successfully reinstalled (reconfiguration starts tomorrow).
