### ISSUE TITLE
Update to v10.9.1

### ISSUE THREAD

**Issue by Thefrank** [Thefrank/jellyfin-server-freebsd#73]
Build:

- [x] Build for FreeBSD.13-x64
- [x] Build for FreeBSD.14-x64

and one of:

- [x] Build Skia [v2.88.4-preview.95](https://github.com/mono/skia/releases/tag/v2.88.4-preview.95)
- [x] Build Skia [Version 2.88.8](https://github.com/mono/SkiaSharp/releases/tag/v2.88.8)

Well, SkiaSharp from 3.0 preview builds cleanly with updated cake!
Downside:
```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (115.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
```

EDIT: 10.9.1 just came out. Guess I am doing that.

**Comment by Thefrank** [comment]
Both build but 2.88.8 seems like the way going forward.
